### ISSUE TITLE
Fatal error: Declaration of execute() in BatchResize.php on line 62

### ISSUE THREAD

**Issue by nielsweb** [xperseguers/t3ext-image_autoresize#100]
- TYPO3 v12.4.11
-  PHP v8.2
- "symfony/console": "7.0.3"
- "causal/image_autoresize": "2.3.0"

When running TYPO3 with this setup, I get this error message:
Fatal error: Declaration of Causal\ImageAutoresize\Command\BatchResize::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /vendor/causal/image_autoresize/Classes/Command/BatchResize.php on line 62

Seems that return type :int is missing in method declaration.
Downgrade symfony/console to v6.4 fixed the problem for me.

**Comment by prathers** [comment]
I can confirm. Get the same error
