### ISSUE TITLE
compatibility 9.4

### ISSUE THREAD

**Issue by DavidBruchmann** [xperseguers/t3ext-image_autoresize#12]
Is there an update for TYPO3 v9.4 in the pipe?
Would be cool as I've just a project with that need.

**Comment by xperseguers** [comment]
Not yet but I don’t expect many compatibility issues, will have a look

**Comment by DavidBruchmann** [comment]
Great, thank's!!!

**Comment by xperseguers** [comment]
After adapting some code in the configuration part (EM), it looks like master branch is compatible with TYPO3 v9. Please test and if you have any problem, open dedicated tickets.
