### ISSUE TITLE
Add support for FAL-based directory references

### ISSUE THREAD

**Issue by froemken** [xperseguers/t3ext-image_autoresize#13]
Hello,

I have entered a valid directory in your task, but it returns me an error:

"Cannot process non-existing directory: 1:/resize_images"

Seems you're working with getFileAbsFileName instead of ResourceFactory::retrieveFileOrFolderObject

Nice greetings

Stefan

**Comment by xperseguers** [comment]
Hello,

What does it mean "I have entered a valid directory in [my] task"?

When you configure the extension in EM, the suggested directories are by default `fileadmin/,upload/`, so you are supposed to provide the same non-FAL format.

**Comment by xperseguers** [comment]
**Requirements**

- Use `1:/,uploads` as default configuration in EM
- Suggest to migrate custom rules if mixing `fileadmin/` with FAL reference
- Keep support for `fileadmin/` (since `uploads/` is not FAL-based anyway)
