### ISSUE TITLE
Auto-Rotate broken in TYPO3 9.5 using GraphicsMagick

### ISSUE THREAD

**Issue by zelcode** [xperseguers/t3ext-image_autoresize#23]
Hi,

maybe related to this:

https://github.com/xperseguers/t3ext-image_autoresize/issues/4

but auto rotation not working on 9.5 and GM, IM is OK.

Regards

**Comment by zelcode** [comment]
Both IM and GM supports `'-auto-orient'`, so (quick and dirty):

```php
    /**
     * Returns a command line parameter to fix the orientation of a rotated picture.
     *
     * @param integer $orientation
     * @return string
     */
    public static function getTransformation($orientation)
    {
        $transformation = '-auto-orient';

        return $transformation;
    }
```

Tested on 8.7 and 9.5, it works so far.

Link: https://github.com/aheckmann/gm/issues/249

**Comment by mz-aimcom** [comment]
Auto-Orientation is enabled by default in TYPO3 v9.

See: https://github.com/TYPO3/TYPO3.CMS/blob/02efc2c224bd4ae56669ad1a860e0dd030c12b66/typo3/sysext/core/Classes/Imaging/GraphicalFunctions.php#L209
