### ISSUE TITLE
release for php 7.3

### ISSUE THREAD

**Issue by Nemo64** [xperseguers/t3ext-image_autoresize#25]
I want to update to php 7.3 but the most recent release claims to mot support php 7.3 while dev-master does.

Any plans for releasing a new version?

**Comment by xperseguers** [comment]
probably in the coming weeks.

**Comment by Nemo64** [comment]
Awesome, thanks for the heads up.

**Comment by nbiwki** [comment]
Hello, I installed your great extension in a PHP 7.3 environment and it looks like everything is working. Are there any problems before PHP 7.3 can be added to the composer.json?
