### ISSUE TITLE
[Suggestion] Default configuration by typoscript

### ISSUE THREAD

**Issue by wtfred** [xperseguers/t3ext-image_autoresize#28]
Hello,

This is not an issue, but a suggestion: it would be nice if we could define a default configuration with typoscript. This way, we could use our own extension to preset things like max_width & max_height.

If you think it's relevant, i could try to make it and PR, i think it would only require to rewrite a bit `ConfigurationController->getDefaultConfiguration()`,  and add `constants.typoscript` & `setup.typoscript`
Thanks for reading :)

**Comment by xperseguers** [comment]
After discussing shortly on Slack, it doesn't make sense to configure the extension in TS as TS is for Frontend whereas we are discussing some Backend processing.

Suggestion is to store the default configuration, e.g., in

```
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['image_autoresize']['defaultConfiguration']
```

which can be defined in a custom extension's `ext_localconf.php`.

**Comment by instruccionesaldorso** [comment]
@xperseguers And why aren't the options saved directly as Extension Manager options and saved in LocalConfiguration.php?
As far as I saw, it always expects a separated file to save the options under "typo3conf/image_autoresize.config.php" and I'd like to get rid of this.

**Comment by xperseguers** [comment]
Because the format used by the extension was not supported by LocalConfiguration which only handles simple key=>value pairs.

**Comment by instruccionesaldorso** [comment]
@xperseguers I don't get it.
And aren't the configuration options simple key => value pairs?

Example: 
`'image_autoresize' => [
            'defaultConfiguration' => [
                'directories' => 'fileadmin/,uploads/',
                'file_types' => 'jpg,jpeg,png',
                'threshold' => '400K',
                'max_width' => '1201',
                'max_height' => '1201',
                'max_size' => '1M',
                'auto_orient' => '1',
                'conversion_mapping' => 'ai => jpg,bmp => jpg,pcx => jpg,tga => jpg,tif => jpg,tiff => jpg',
                'keep_metadata' => '0',
                'resize_png_with_alpha' => '0',
            ]
        ]`

**Comment by xperseguers** [comment]
have a look at the rules you may create...

**Comment by instruccionesaldorso** [comment]
Ah, ok, I understand. We left that section empty for now in our case. I see now that nested format.
Thanks for the feedback!

**Comment by instruccionesaldorso** [comment]
Sorry to jump into this issue again. I tried to follow your suggestion and I added this in my custom extension under ext_localconf.php file:

$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['image_autoresize']['defaultConfiguration'] = [
    'directories' => 'fileadmin/,uploads/',
    'file_types' => 'jpg,jpeg,png',
    'threshold' => '400K',
    'max_width' => '1200',
    'max_height' => '1200',
    'max_size' => '1M',
    'auto_orient' => '1',
    'conversion_mapping' => 'ai => jpg,bmp => jpg,pcx => jpg,tga => jpg,tif => jpg,tiff => jpg',
    'keep_metadata' => '0',
    'resize_png_with_alpha' => '0',
];

But my parameters are not being taken into account under EM settings, only the default ones from Classes/Controller/ConfigurationController::getDefaultConfiguration()

**Comment by instruccionesaldorso** [comment]
However, GLOBALS array is overwritten by my settings, as I can see from SYSTEM > Configuration BE module. 
Is it normal that I cannot see them overwritten under EM global settings, I guess?

**Comment by instruccionesaldorso** [comment]
https://github.com/xperseguers/t3ext-image_autoresize/blob/master/Classes/Controller/ConfigurationController.php#L421

**Comment by wtfred** [comment]
> 
> 
> Sorry to jump into this issue again. I tried to follow your suggestion and I added this in my custom extension under ext_localconf.php file:
> 
> $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['image_autoresize']['defaultConfiguration'] = [
> 'directories' => 'fileadmin/,uploads/',
> 'file_types' => 'jpg,jpeg,png',
> 'threshold' => '400K',
> 'max_width' => '1200',
> 'max_height' => '1200',
> 'max_size' => '1M',
> 'auto_orient' => '1',
> 'conversion_mapping' => 'ai => jpg,bmp => jpg,pcx => jpg,tga => jpg,tif => jpg,tiff => jpg',
> 'keep_metadata' => '0',
> 'resize_png_with_alpha' => '0',
> ];
> 
> But my parameters are not being taken into account under EM settings, only the default ones from Classes/Controller/ConfigurationController::getDefaultConfiguration()

Well my pull request resolving this issue hasn't been accepted yet, so it's normal that your configuration is not taken in account ^^

**Comment by instruccionesaldorso** [comment]
Thanks for the feedback!
I applied your patch while it's still not merged.
It works like a charm ;)

**Comment by instruccionesaldorso** [comment]
@xperseguers Could you check the pull request by @wtfred and merge it into `master` branch, if that's ok for you, for us not to have to apply the patch in our projects?
