### ISSUE TITLE
Scheduler task configuration lost after save & close

### ISSUE THREAD

**Issue by echavaillaz** [xperseguers/t3ext-image_autoresize#34]
Hi,

In TYPO3 9, the scheduler task configuration is lost after saving and close.
If you try just to save it is ok.

Thanks

**Comment by xperseguers** [comment]
After discussing, here is an updated description:

- In TYPO3 v9, if you click the button "save" no problems are reported
- If you reedit the task, all additional fields seem to be lost (they are blank again)
- If you check the database, the fields are however properly persisted

I did not check if those fields are actually properly taken into account when **executing** the task afterwards but while editing again, it looks like somehow they are not properly fetched again for editing.

**Comment by xperseguers** [comment]
After quickly checking, if you run the task, it will work, so the bug is really only while re-editing a properly configured task.
