### ISSUE TITLE
keep_metadata = 1

### ISSUE THREAD

**Issue by ursbraem** [xperseguers/t3ext-image_autoresize#36]
Hi Xavier! 

Is it correct that `keep_metadata` is set 0 by default? I wasn't sure where I see it in the extension.

We had quite a session to find out not only TYPO3 strips metadata out of images, but also image_autoresize.
There is an issue with firefox that causes sRGB images without the correct color profile information to display oversaturated. 

While I find it best practice to strip other maybe confidential metadata (cf. [Harry Potter](https://www.eff.org/de/deeplinks/2007/07/harry-potter-and-digital-fingerprints)), I think color profiles shouldn't be stripped out by default. Or?

To avoid long debugging sessions like ours, **I would propose to set `keep_metadata = 1` as default value.**

(same in TYPO3...: `[GFX][processor_stripColorProfileByDefault]` and `[GFX][processor_stripColorProfileCommand]`, but I'll wait for your feedback to see if I should open a request on forge)

Best
Urs

**Comment by xperseguers** [comment]
Hello Urs, well, I'd be fine keeping the color profile. As you say, it makes sense to keep it, but other metadata should for sure be stripped *by default*. Yet, I'm not sure we can ask to keep color profile but strip everything else, did not self investigate, did you?

**Comment by ursbraem** [comment]
I didn't. Well, I did venture a little into `exiftool` and similar in this investigation. I think it depends on the graphics processor the hosting uses, else why would the core demanding a `processor_stripColorProfileCommand`... Probably this is too complex and error prone to set as default.
