### ISSUE TITLE
Error in scheduler because of flash message in TYPO3 9 LTS

### ISSUE THREAD

**Issue by webian** [xperseguers/t3ext-image_autoresize#37]
Hello,
in this use case with TYPO3 9 LTS I have a scheduler that creates images so image_autoresize tries to resize them and display the flash messages. But then this error happens:
`Argument 1 passed to TYPO3\\CMS\\Core\\Session\\Backend\\DatabaseSessionBackend::update() must be of the type string, null given, called in /typo3/sysext/core/Classes/Authentication/AbstractUserAuthentication.php on line 1311`

I'm not sure but maybe we should check if we are in CLI in this place:
https://github.com/xperseguers/t3ext-image_autoresize/blob/8466f4aaefc89e54eef649e4e93f65e220c0da8e/Classes/Slots/FileUpload.php#L247
changing the condition this way `(TYPO3_MODE !== 'BE' || php_sapi_name() == 'cli')` so it will not try to flash messages if run by scheduler.

**Comment by xperseguers** [comment]
> changing the condition this way (TYPO3_MODE !== 'BE' || php_sapi_name() == 'cli') so it will not try to flash messages if run by scheduler.

To be in line with the various TYPO3 versions supported, I would suggest:

```
if (TYPO3_MODE !== 'BE' || PHP_SAPI === 'cli') {
    return;
}
```

**Comment by webian** [comment]
Sorry @xperseguers but I encountered this problem again.
Checking the code I found [this condition](https://github.com/xperseguers/t3ext-image_autoresize/blob/ad3e2f0e3e9a5a875afc98ed6ae6435d70081b99/Classes/Task/BatchResizeTask.php#L152). But AFAIK [_cli_user *must* be administrator](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.6/Feature-79240-SingleCliUserForCliCommands.html).

Could it be that we use the same condition `(TYPO3_MODE !== 'BE' || PHP_SAPI === 'cli')` here to set the `$callbackNotification`? If that condition is true we use 'syslog' if not we use 'notify'.

**Comment by xperseguers** [comment]
yes, this seems to make sense. Want to create a PR?

**Comment by webian** [comment]
Sure! Done.
