### ISSUE TITLE
Leftover record in sys_file table

### ISSUE THREAD

**Issue by webian** [xperseguers/t3ext-image_autoresize#38]
Using a code like this:
```
$image = $storage->addFile(
    '/domain.ext/htdocs/typo3temp/var/transient/tmp_file.bmp',
    $targetFolder,
    'target_name.bmp',
    DuplicationBehavior::REPLACE,
    true
);
```
the BMP file is correctly converted to a JPG with filename `target_name.jpg` with its own record in `sys_file` but a record for the transient tmp_file.bmp is left in `sys_file` table.

**Comment by xperseguers** [comment]
Did you check when uploading via drag and drop in the Backend, do you get the same problem?

**Comment by webian** [comment]
No problem uploading via drag & drop in the Backend.

**Comment by xperseguers** [comment]
Just tested with that exact same code you suggest in a TYPO3 v12 install and current master and there are absolutely to leftover in table `sys_file` as the file is really renamed/processed `before` it gets inserted into that table, thus at no point in the workflow we find a "bmp" entry in that table.
