### ISSUE TITLE
Signal/slot to post-process the configuration

### ISSUE THREAD

**Issue by wtfred** [xperseguers/t3ext-image_autoresize#40]
Hello!

Months after, i'm testing your implementation of signal/slot.

It's working, but it's not the behaviour i had in mind when i made my PR #29 at the time.

The current behaviour with the signal slot, is: when an extension connects to the signal, the configuration is always taken from the there. That mean you can't define your own configuration inside the extension manager.

What i suggest is either dispatching the signal only when the default configuration is retrieved, like this:
```
    /**
     * @return array
     */
    public static function readConfiguration(): array
    {
        $configurationFileName = static::getConfigurationFileName();

        $configuration = file_exists($configurationFileName) ? include($configurationFileName) : [];
        if (!is_array($configuration) || empty($configuration)) {
            $configuration = static::getDefaultConfiguration();
            $signalSlotDispatcher = GeneralUtility::makeInstance(\TYPO3\CMS\Extbase\SignalSlot\Dispatcher::class);
            $signalSlotDispatcher->dispatch(
                __CLASS__,
                static::SIGNAL_ProcessConfiguration,
                [
                    'configuration' => &$configuration,
                ]
           );
        }

        return $configuration;
    }
```

Or dispatching another signal for this purpose only.
```
    const SIGNAL_ProcessDefaultConfiguration = 'processDefaultConfiguration';

    /**
     * @return array
     */
    public static function readConfiguration(): array
    {
        $configurationFileName = static::getConfigurationFileName();

        $configuration = file_exists($configurationFileName) ? include($configurationFileName) : [];
        if (!is_array($configuration) || empty($configuration)) {
            $configuration = static::getDefaultConfiguration();
            $signalSlotDispatcher = GeneralUtility::makeInstance(\TYPO3\CMS\Extbase\SignalSlot\Dispatcher::class);
            $signalSlotDispatcher->dispatch(
                __CLASS__,
                static::SIGNAL_ProcessDefaultConfiguration ,
                [
                    'configuration' => &$configuration,
                ]
           );
        }

        $signalSlotDispatcher = GeneralUtility::makeInstance(\TYPO3\CMS\Extbase\SignalSlot\Dispatcher::class);
        $signalSlotDispatcher->dispatch(
            __CLASS__,
            static::SIGNAL_ProcessConfiguration,
            [
                'configuration' => &$configuration,
            ]
        );

        return $configuration;
    }
```

This way, an extension could "propose" its own default configuration, but the admin would always have the final words on the configuration he wanted by using the extension manager.

If this is relevant to you, i can make the PR with the behaviour you like the most.

Thanks!

**Comment by xperseguers** [comment]
I get what you suggest but can hardly think of a real-life use case... "proposing" a default configuration sounds like some web hoster having the extension ready-to-install to users with meaningful defaults but letting the integrator have the final word. What I implemented is some integrator providing the configuration in any way based on knowing the environment and willing to, e.g., persist and keep track of it in a versioning system.

I really don't get why you seem to think it's important to suggest defaults but let the administrator change that.

**Comment by wtfred** [comment]
Well for example, bootstrap_package could propose a default configuration for image_autoresize, but the final user would be allowed to have the final word in the extension module, without having to write some code.

**Comment by xperseguers** [comment]
Hi, quite some time, sorry, but coming again :) I like having a dedicated signal when no configuration exists, I find it much more clear and best to be then included by e.g., bootstrap_package
