### ISSUE TITLE
Adding file without backend connection

### ISSUE THREAD

**Issue by jlimassetEm** [xperseguers/t3ext-image_autoresize#43]
Hi,

In our extension, connected fe_users can update their image. When a file is uploaded, it's added like this : 
`$file = $storage->addFile($fileTmpMedia, $folder, $fileMedia);`
This raises an error from class CoreResourceStorageEventListener.php in processFile and sanitizeFileName functions because getBackendUser() cannot return null :
 
![image](https://user-images.githubusercontent.com/68337099/92447150-2a58e700-f1b7-11ea-9573-8229c820e35c.png)

Thanks!

**Comment by xperseguers** [comment]
This is supposed to be fixed for a while now. Please see #35, the method you show, `getBackendUser()` is not the one that I read in current code.

**Comment by villamarianne** [comment]
This also happens in cli context with a symfony command controller.

My quick fix was to change

https://github.com/xperseguers/t3ext-image_autoresize/blob/329bfbe2b38fd6f7676fe5f3655d4a7eb7c73950/Classes/EventListener/CoreResourceStorageEventListener.php#L232

to

`if (TYPO3_MODE !== 'BE' || PHP_SAPI === 'cli') {`


<img width="1243" alt="Screenshot 2020-10-08 235043" src="https://user-images.githubusercontent.com/15908849/95517430-466fc400-09c1-11eb-85fa-b70271a67e83.png">
