### ISSUE TITLE
Image resized even if smaller than the limit

### ISSUE THREAD

**Issue by webian** [xperseguers/t3ext-image_autoresize#45]
Hi @xperseguers !
I noticed that uploading a JPG image 1600x1200, it was auto-resized to the same size 1600x1200 even if smaller than the size limit that is 1920x1920.

Debugging the code I found that image_autoresize create a temp file from the original image in any case and then [checks if the temp image is still bigger](https://github.com/xperseguers/t3ext-image_autoresize/blob/ad1b756d5d4b12ba33f303534b2c6794a322b419/Classes/Service/ImageResizer.php#L353) and if it is then it discard it.

In this case, since the original image has the smallest JPG compression, the recreated tmp image is smaller than those hardcoded 10KB and so the original image is replaced by the tmp one. But this is not the wanted behavior at least in this use case.

I'm not sure about the solution for this use case. Maybe make the 10KB configurable?

**Comment by xperseguers** [comment]
Hello. In the configuration you have a trigger on the file size (not dimensions), if that file size is exceeded, then the resizing process is triggered. I suspect that in your case your file size is larger than the trigger limit and this is the reason why it gets resized, nothing strange as I can see.

**Comment by webian** [comment]
I think I have misrepresented the problem.

Suppose:
1) image_autoresize configured size limit is 1920x1920
2) user upload a JPG with dimensions 1600x1200 and size 100KB named test.jpg
3) this test.jpg has a low JPG compression (better quality and bigger file size)

What is expected:
the uploaded image is preserved because its dimensions are smaller than the image_autoresize configured size limit.

What happens:
[Here](https://github.com/xperseguers/t3ext-image_autoresize/blob/ad1b756d5d4b12ba33f303534b2c6794a322b419/Classes/Service/ImageResizer.php#L353) image_autoresize always creates a tmp image from test.jpg.

Suppose that this tmp image file size is 85KB.

[Here](https://github.com/xperseguers/t3ext-image_autoresize/blob/ad1b756d5d4b12ba33f303534b2c6794a322b419/Classes/Service/ImageResizer.php#L353) image_autoresize won't skip the tmp file even if the dimensions are smaller than the image_autoresize configured size limits.
It won't skip the tmp file because 85KB < 100KB - 10KB.

This results in a JPG compressed a second time by image_autoresize when there's no need to do it.

**Comment by xperseguers** [comment]
> This results in a JPG compressed a second time by image_autoresize when there's no need to do it.

I disagree here, you are missing an important point of the purpose of this extension...

That's explained in the introduction chapter of the documentation (https://docs.typo3.org/p/causal/image_autoresize/2.1/en-us/Introduction/Index.html):

> [...] After all, if an editor managed to create a picture of many mega-pixels that weights only a few KB, why should we bother?

That's the key point here. The goal was never to resize down to prevent having gigantic number of pixels, but to resize down to some "sane" number of pixels, so that the **footprint** gets smaller. Purpose of a smaller footprint is lower footprint for backup but above all, when you ask TYPO3 to prepare a gallery, the generation of thumbnails takes ages not when there's a huge number of pixels, but when the files are heavy.

**Comment by webian** [comment]
Ok. I was taking into consideration only the pixel dimensions of the image without considering the file size threshold.
