### ISSUE TITLE
Problems related to cropVariants

### ISSUE THREAD

**Issue by cleicht** [xperseguers/t3ext-image_autoresize#46]
If you use image_autoresize together with cropVariants, there are problems with the selection of the crop. If you have an image with 5760 x 3840px and calculate it down to 1200 x 800, cropVariants uses the 5760 x 3840px as a starting point and calculates errors. After the conversion, the size of the picture in sys_file_metadata remains unchanged.

**Comment by xperseguers** [comment]
It's unclear how to reproduce. Please attach a sample image and describe exactly step-by-step (including your configuration) what to do to reproduce the problem and understand what needs to get fixed.

**Comment by fritzdacat** [comment]
What about this issue? Is it possible to use the extension without any problems in an already existing web and to resize all previously uploaded images using the scheduler without causing problems with the CropVariants?

**Comment by dogawaf** [comment]
At least on TYPO3 11, the position of the crop area are stored in percent of the size of the image.
So, if the underlying image has changed dimensions, the stored crop data is still valid.

```json
{"headline":{"cropArea":{"height":0.4362818590704648,"width":0.436,"x":0.425,"y":0.22488755622188905},"selectedRatio":"3:2","focusArea":null},
"rebound":{"cropArea":{"height":0.34332833583208394,"width":0.343,"x":0.49,"y":0.22188905547226387},"selectedRatio":"3:2","focusArea":null}}
```

**Comment by xperseguers** [comment]
closed due to lack of further info from @cleicht and info from @dogawaf showing `cropArea` is stored in percent.
