### ISSUE TITLE
Resizing does not work on certain settings

### ISSUE THREAD

**Issue by thasmo** [xperseguers/t3ext-image_autoresize#47]
```php
<?php
return [
    'directories' => '1:/',
    'file_types' => 'jpg,jpeg,png',
    'threshold' => '5120K',
    'max_width' => '5120',
    'max_height' => '3840',
    'max_size' => '100M',
    'auto_orient' => '1',
    'conversion_mapping' => 'ai => jpg,bmp => jpg,pcx => jpg,tga => jpg,tif => jpg,tiff => jpg',
    'keep_metadata' => '1',
    'resize_png_with_alpha' => '1',
];
```

Image is resized to `11107x7536`. Why? I would expect it to be resized to a dimension where either width is `5120` or height is `3840` but not some random size.

**Comment by thasmo** [comment]
Same happens with this config.
```php
<?php
return [
    'directories' => '1:/',
    'file_types' => 'jpg,jpeg,png',
    'threshold' => '5120K',
    'max_width' => '5120',
    'max_height' => '5120',
    'max_size' => '',
    'auto_orient' => '1',
    'conversion_mapping' => 'ai => jpg,bmp => jpg,pcx => jpg,tga => jpg,tif => jpg,tiff => jpg',
    'keep_metadata' => '1',
    'resize_png_with_alpha' => '0',
];
```

**Comment by thasmo** [comment]
When using this config, the file **suddenly** gets resized to `3773x2560`.
```php
<?php
return [
    'directories' => '1:/',
    'file_types' => 'jpg,jpeg,png',
    'threshold' => '5120K',
    'max_width' => '5120',
    'max_height' => '2560',
    'max_size' => '',
    'auto_orient' => '1',
    'conversion_mapping' => 'ai => jpg,bmp => jpg,pcx => jpg,tga => jpg,tif => jpg,tiff => jpg',
    'keep_metadata' => '1',
    'resize_png_with_alpha' => '0',
];
```

**Comment by xperseguers** [comment]
It gets *resized* to 11107x7536? and what was the original dimensions?

**Comment by thasmo** [comment]
@xperseguers Ah, pardon me. I'm sorry, it seems it does not get resized at all because `11107x7536` are the original dimensions. That is weird.

**Comment by thasmo** [comment]
```
'max_width' => '5120',
'max_height' => '2560',
```
does not work but
```
'max_width' => '5120',
'max_height' => '2560',
```
does resize the image using `2560` as its final height.

**Comment by xperseguers** [comment]
Did you check the filesize before resizing and the filesize while resizing to 5120x5120? that could be the reason why it doesn't get resized

**Comment by thasmo** [comment]
Could it be that there's some more or less complex aspect ratio related check or various checks on combinations of width/height which fails on certain values/ratios?

**Comment by xperseguers** [comment]
It's hard to debug without a concrete example, would it be possible to have a picture leading to this "faulty" behaviour?

**Comment by thasmo** [comment]
@xperseguers The filesize changed from `18.6 MB` to `14.5 MB` indeed, but what is this based on? Why would it not resize the image in this case?

**Comment by thasmo** [comment]
In the end [the issue was the disk cache size](https://github.com/ImageMagick/ImageMagick/issues/396) of `1GB`. After increasing it to `5GB` in my case, resizing the image works as expected.
