### ISSUE TITLE
4th Argument of indexFile must be of type int, float given

### ISSUE THREAD

**Issue by froemken** [xperseguers/t3ext-image_autoresize#48]
Hello,

while uploading a file in FE context I get the error message:

Argument 4 passed to Causal\ImageAutoresize\Utility\FAL::indexFile() must be of type int, float given, called in ...CoreResourceStorageEventListener.php on line 192

Can you please cast the values of static::$metadata['COMPUTED']['Width'] and static::$metadata['COMPUTED']['Height'] in FileUpload.php to int?

Nice greetings

Stefan

**Comment by mediaessenz** [comment]
Please also in the CoreResourceStorageEventListener Class
