### ISSUE TITLE
4th Argument of indexFile must be of type int, float given

### ISSUE THREAD

**Issue by mediaessenz** [xperseguers/t3ext-image_autoresize#50]
The same problem already fixed inside Causal\ImageAutoresize\Slots\FileUpload exists inside CoreResourceStorageEventListener 

Will sent pull request to fix it ...

**Comment by xperseguers** [comment]
isn't it fixed in the mean time, few minutes after you commented on the closed ticket? :)

**Comment by mediaessenz** [comment]
Sorry, my fault

**Comment by xperseguers** [comment]
no problem, by chance I've seen your comment :)

**Comment by mediaessenz** [comment]
Ah, you just fixed it? That's why I didn't found the problem in the just forged version.
