### ISSUE TITLE
Resizing not working in 9.5.30?

### ISSUE THREAD

**Issue by christophbee** [xperseguers/t3ext-image_autoresize#53]
I installed the plugin (v2.1.1) in Typo3 9.5.30 and set configuration this way: 
![Bildschirmfoto 2021-08-30 um 15 52 36](https://user-images.githubusercontent.com/22295289/131350421-5c83117c-d8c0-4f49-95cd-baaf6d31a35a.png)

When I upload an image to "/fileadmin/" nothing happens with that uploaded image (3.2 MB)
![Bildschirmfoto 2021-08-30 um 15 53 27](https://user-images.githubusercontent.com/22295289/131350501-81e34484-aad7-484e-bf22-4b772e3cb6fe.png)

Any idea what's going wrong here?

**Comment by xperseguers** [comment]
no feedback for a long time and upcoming version won't support TYPO3 v9 anymore.
