### ISSUE TITLE
Resize not working anymore for editors, if folder is set to 1:/user_upload/,uploads/

### ISSUE THREAD

**Issue by claude27** [xperseguers/t3ext-image_autoresize#61]
Resize is not working anymore for editors without admin rights, if the folder is set to "1:/user_upload/,uploads/".
Only "1:/,uploads/" is working.

TYPO3 10.4.23
image_autoresize 2.1.1
extractor 2.1.0
PHP 7.4
Composer based Installation

I discovered this by hazard. Some month or perhaps already one year ago with TYPO3 9.5 is still worked, I think.
Rulesets are not working too, but they also didn't work before.

![grafik](https://user-images.githubusercontent.com/4347809/154236090-bab3d906-2339-418c-a991-53b07d912ea8.png)

**Comment by xperseguers** [comment]
Don't know how to reproduce. Just tried as a non TYPO3 admin in TYPO3 v10 and it worked (I used the method which allows to upload right away while redacting a EXT:news record - media)

**Comment by brunick** [comment]
Hi, 
we've encountered this problem as well - but actually no one can upload `png` files, if they're above the set resoulution.
i got an error message here for you

```
Tue, 21 Mar 2023 08:22:26 +0100 [CRITICAL] request="d031c142878b9" 
component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": 
Core: Exception handler (WEB: BE): TypeError, code #0, file 
/var/www/releases/20230308130949Z/public/typo3conf/ext/image_autoresize/Classes/Event/ImageResizedEvent.php, 
line 47: Causal\ImageAutoresize\Event\ImageResizedEvent::__construct(): Argument #4 ($newWidth) must be of type int, string given, 
called in /var/www/releases/20230308130949Z/public/typo3conf/ext/image_autoresize/Classes/Service/ImageResizer.php on line 380 - 
{
    "mode":"WEB",
    "application_mode":"BE",
    "exception_class":"TypeError",
    "exception_code":0,
    "file":"/var/www/releases/20230308130949Z/public/typo3conf/ext/image_autoresize/Classes/Event/ImageResizedEvent.php",
    "line":47,
    "message":"Causal\\ImageAutoresize\\Event\\ImageResizedEvent::__construct(): Argument #4 ($newWidth) must be of type int,string given, called in /var/www/releases/20230308130949Z/public/typo3conf/ext/image_autoresize/Classes/Service/ImageResizer.php on line 380",
    "request_url":"https://<redacted>/typo3/ajax/file/process?token=--AnonymizedToken--","exception":null
}
```

The Server is running TYPO3 Version 11.5.24
PHP Version 8.1.16
Composer mode

**Comment by xperseguers** [comment]
Which version of the extension are you using?

These are the current lines:

```php
            $event = $eventDispatcher->dispatch(new ImageResizedEvent(
                ($fileName === $destFileName) ? 'RESIZE' : 'RESIZE_CONVERT',
                $fileName,
                $tempFileInfo[3],
                (int)$tempFileInfo[0],
                (int)$tempFileInfo[1]
            ));
```

the `$newWidth` and the `$newHeight` arguments are the 2 last ones and both are casted to an int since 30.11.2022, as part of #66.

Oh... looks like there wasn't any new release since then...

Please double-check master branch fixes your problem and report here. Thanks.

**Comment by brunick** [comment]
thanks for you ur reply, 
we're using v2.2.0 with almost stock settings. i'll check if the master works :)
