### ISSUE TITLE
Undefined variable $_EXTKEY throws exception

### ISSUE THREAD

**Issue by thasmo** [xperseguers/t3ext-image_autoresize#62]
When using the extension with TYPO3 v11 this exception comes up:

```
PHP Warning: Undefined variable $_EXTKEY in /app/public/typo3conf/ext/image_autoresize/ext_localconf.php line 27
```

[TYPO3 documentation](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/ConfigurationFiles/Index.html) states:

> Changed in version 10.0: These variables are no longer declared in ext_tables.php and ext_localconf.php files: $_EXTKEY, $_EXTCONF, T3_SERVICES, T3_VAR, TYPO3_CONF_VARS, TBE_MODULES, TBE_MODULES_EXT, TCA, PAGES_TYPES, TBE_STYLES

It seems that `$_EXTKEY` should not be used within `ext_localconf.php` anymore, because TYPO3 does not set it anymore. This sounds like it is the reason for the exception.

Do I miss something here or why would this exception be thrown? Thanks a lot!

**Comment by DavidBruchmann** [comment]
in branch master $_EXTKEY should be filled with the parameter for `(static function (string $_EXTKEY) {` which you find at the end of the file: `})('image_autoresize');`.
It might be though that you use PHP 8 where I don't know about changes or behavior yet.

**Comment by thasmo** [comment]
Ow! I realized that the `ext_localconf.php` file, in my case, was missing the static function wrapper - and so I figured that composer was installing quite an old version of the extension, in fact version `1.6.0`.

For now I'm using `composer require --ignore-platform-reqs causal/image_autoresize:^2.1.1` to install the latest version.

**Comment by DavidBruchmann** [comment]
With TYPO3 11 the static wrapper is not advised anymore, but it's neither disturbing.  
At least without that wrapper the variable had to be assigned differently.

**Comment by thasmo** [comment]
> With TYPO3 11 the static wrapper is not advised anymore, but it's neither disturbing.

[Is that so?](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/ConfigurationFiles/Index.html?highlight=ext_localconf#rules-and-best-practices)
> You SHOULD use a directly called closure function to encapsulate all locally defined variables and thus keep them out of the surrounding scope. This avoids unexpected side-effects with files of other extensions.

**Comment by DavidBruchmann** [comment]
You can read about the reason here:

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.4/Important-94280-MoveContentsOfExtPhpIntoLocalScopes.html?highlight=ext_localconf%20php

**Comment by thasmo** [comment]
I think that change note is about using `namespace` within those files; this is not referring to using static functions to define scope.

**Comment by DavidBruchmann** [comment]
You influence the caching behavior by wrapping. So without wrap you can avoid clearing the whole cache which can take quite some time on big sites to build up again.

**Comment by DavidBruchmann** [comment]
"must not" is quite categorically 
![image](https://user-images.githubusercontent.com/999146/161120376-c120d78f-9dd1-429f-8fa4-efbe9e0d975b.png)

**Comment by xperseguers** [comment]
The warning and "must not" is really about namespacing, not closure as I do, but the remark regarding code sniffing while using a (local) `$_EXTKEY` is a good point. Will think about it in the future.
