### ISSUE TITLE
Any news about PHP 8 compatibility? 

### ISSUE THREAD

**Issue by subnoodle** [xperseguers/t3ext-image_autoresize#63]
Dear Xavier,
do you have any plans to lift imageautoresize to PHP versions 8.0 / 8.1?
Would be great - using you extension in projects where it is the last not working with php > 7.
Thank you very much for your information,
Thomas

**Comment by Patta** [comment]
It seems that the master branch is ready for PHP 8.

**Comment by subnoodle** [comment]
Thank you Patta, that's a helpful hint. So, i'm looking forward to the next release / version.

**Comment by thasmo** [comment]
@xperseguers, are there plans to release the current master for official PHP 8.x compatibility? We're running TYPO3 v11 on PHP 8.0 and would love to use the exension. :) Thanks a lot!

**Comment by xperseguers** [comment]
@thasmo Please double check master branch, would love to get some feedback that it still works fine for you in v11, thanks.

Then I plan to release a new version.

**Comment by thasmo** [comment]
@xperseguers, thanks! Hadn't had any time yet to test it, but I'll surely report back if things don't work. :sweat_smile: Nonetheless, thanks a lot for your work! :+1:
