### ISSUE TITLE
TYPO3_REQUEST error using cli command

### ISSUE THREAD

**Issue by valentin-** [xperseguers/t3ext-image_autoresize#69]
Hi, related to https://github.com/xperseguers/t3ext-image_autoresize/issues/68 there is still a request issue in the ImageResizer file.

![image](https://user-images.githubusercontent.com/90033/207361659-1e079afb-48c2-442b-bde5-758ddb376bc3.png)

**Comment by xperseguers** [comment]
Hi @valentin-, would you mind trying this?

Edit file `Classes/Service/ImageResizer.php` and replace the body of `function localize` (around line 451 where it fails) with that:

```
return \TYPO3\CMS\Extbase\Utility\LocalizationUtility::translate($input);
```

I guess it will solve that issue...

**Comment by valentin-** [comment]
@xperseguers yes that's working.
