### ISSUE TITLE
TYPO3 v9.5 - Problem with image resizing on AWS

### ISSUE THREAD

**Issue by zkrechowiec** [xperseguers/t3ext-image_autoresize#72]
Hi !
I have a problem resizing my image that is uploaded to AWS. When I upload an image bigger than the size I have restricted, nothing happens and my image is just added as is. Is there a special configuration when using an AWS file storage ?
ImageMagick is working correctly and I am using TYPO3 in 9.5.39 version and image_autoresize in 2.1.1 version.
Thank you in advance for your help

**Comment by xperseguers** [comment]
Hi, according to the documentation (https://docs.typo3.org/p/causal/image_autoresize/2.2/en-us/KnownProblems/Index.html) only `LocalStorage` has been implemented and tested.

I guess you are using EXT:aus_driver_amazon_s3 to connect to AWS and if so, based on https://github.com/andersundsehr/aus_driver_amazon_s3/blob/master/Classes/Driver/AmazonS3Driver.php#L55 the type of driver is `AusDriverAmazonS3` and not `LocalStorage` and thus it just cannot work at this stage.
