### ISSUE TITLE
Invalid method signature which blocks Scheduler-Creation

### ISSUE THREAD

**Issue by weisgerberm** [xperseguers/t3ext-image_autoresize#73]
Hi,
when I try to add any scheduler task, I'll get this error:

> Fatal error: Declaration of Causal\ImageAutoresize\Task\fakeSchedulerModuleController::addMessage($message, $severity = TYPO3\CMS\Core\Messaging\FlashMessage::OK) must be compatible with TYPO3\CMS\Scheduler\Controller\SchedulerModuleController::addMessage(TYPO3\CMS\Backend\Template\ModuleTemplate $moduleTemplate, string $message, TYPO3\CMS\Core\Type\ContextualFeedbackSeverity $severity = TYPO3\CMS\Core\Type\ContextualFeedbackSeverity::OK): void in /home/___/domains/___/typo3/vendor/causal/image_autoresize/Classes/Task/BatchResizeAdditionalFieldProvider.php on line 168

My setup is TYPO3 12.2 in Composer Mode with PHP 8.1
The extension is in version 2.2.0

**Comment by xperseguers** [comment]
This is related to https://forge.typo3.org/issues/87193 and only happens with TYPO3 v12.

**Comment by dogawaf** [comment]
Duplicate of #70 ?
