### ISSUE TITLE
Setting keep_metadata to false is not respected

### ISSUE THREAD

**Issue by dogawaf** [xperseguers/t3ext-image_autoresize#74]
Hi

On the TYPO3 setup, without image_autoresize, metadata are ignored thanks to the default option `TYPO3_CONF_VARS/GFX/processor_stripColorProfileCommand=+profile '*'`.

If I install image_autoresize and if I set keep_metadata to false, and import an image with exif description, that description is stored into sys_file_metadata.
I would expect setting keep_metadata to false strip out any image's metadata.

**Comment by xperseguers** [comment]
That's the case, the file will not retain the EXIF data if you set `keep_metadata` to `false`. However, as documented, the extension will still extract everything it can while resizing, *before* stripping metadata.

If you choose to `keep_metadata`, then the EXIF will be extracted exactly the same way, but in addition your resized file will keep those metadata in the file itself.

I don't really see why you wouldn't want to put everything you can into `sys_file_metadata`. I mean if you make use of it, you have the info, if you don't, that doesn't really take much place anyway...

**Comment by dogawaf** [comment]
Alright, I misunderstood the `keep_metadata` option. `keep_metadata=false` keeps the default `+profile '*'` in the IM command, so the metada are stripped out from resulting image **file**, but the metadata are still stored in **`sys_file_metadata`**.

The use case is: the customer buys an image on shutterstock, this image is filled with many keywords. The image is uploaded in TYPO3, and displayed in a textmedia. The shutterstock keywords are displayed under the image.
The customer does not wan't to keep those keywords, because there describe the image in a wrong language, and not with a proper sentence. He does not wan't either to edit manually each time the metadata to clear the file.

![image](https://user-images.githubusercontent.com/381969/223255118-2a9974b5-07c9-4f48-8b55-b482a7f8b5a0.png)

A workaround is to patch the extension in order to remove the populateMetadata eventlistener.
