### ISSUE TITLE
Extension always extracting metadata / "Automatically extract metadata after upload" from storage configuration not respected

### ISSUE THREAD

**Issue by ffh-webadmin** [xperseguers/t3ext-image_autoresize#75]
As soon as image_autoresize is enabled all EXIF / IPTC metadata will be extracted from the image and stored to sys_file_metadata even the option "Automatically extract metadata after upload" in FAL storage configuration is disabled.

**Comment by xperseguers** [comment]
Rationale is that once rescaled, the image is likely to loose metadata (for the sake of saving as much spaces as possible).

Your proposal would only make sense if the resize rule keeps the metadata.

The option to not extract metadata right away for a FAL storage is afaik bound to the lack of knowledge from TYPO3 for the expanded time needed to extract metadata as it depends on the extractor in use. Moreover, it may be unavailable for non-local storages. Now, the extraction is done in that case for local-only storages, and resizing takes some time already, so what's the exact problem taking the chance to extract available metadata during that process? Can you elaborate?

**Comment by xperseguers** [comment]
OK, if we speak about privacy, I'd say it's "legit", I didn't consider this. It's a bit "edge" anyway as if someone really wants to protect themselves from privacy and GDPR issues, they shouldn't upload privacy-related information at all and expect the targeting system to take care of stripping away everything...

But OK, I guess it's quite fine to take the storage's configuration option into account.
