### ISSUE TITLE
[Feature] PHP 8.2 support

### ISSUE THREAD

**Issue by bh-teufels** [xperseguers/t3ext-image_autoresize#78]
Hello,

i wanted to try the Extension with 
TYPO3 12.4.3 
PHP 8.2.2

but could not be installed with composer because of
`causal/image_autoresize 2.2.0 requires php >=7.4.0 <=7.4.99 || >=8.0.0 <=8.1.99 -> your php version (8.2.2) does not satisfy that requirement.`

i see the PHP 8.2 support already added but not tagged yet. 
Are there any plans when to publish the last adjustments?

thank you

**Comment by xperseguers** [comment]
I'll do it soon. Thanks for the reminder.
