### ISSUE TITLE
Settings file?

### ISSUE THREAD

**Issue by eiranix** [xperseguers/t3ext-image_autoresize#81]
I want to set the max width/height however the settings are not being saved.
This is probably because it's trying to write a file to a read-only folder.
So my quesiton is where is the file that stores these settings supposed to be located? (So I can allow write access for it)
Or is there another way to manually apply these settings?

**Comment by xperseguers** [comment]
Same directory as your LocalConfiguration.php

**Comment by xperseguers** [comment]
See https://github.com/xperseguers/t3ext-image_autoresize/blob/master/Classes/Controller/ConfigurationController.php#L563-L571
