### ISSUE TITLE
Changes in ExtensionManagerEventListener cause CSP error 

### ISSUE THREAD

**Issue by jpgreth** [xperseguers/t3ext-image_autoresize#83]
When using the latest 2.2.1 with CMS 12.4.5 and activated backend CSP. The inline script in `\Causal\ImageAutoresize\EventListener\ExtensionManagerEventListener` causes a CSP-error.

![CSP Error](https://github.com/xperseguers/t3ext-image_autoresize/assets/2305066/328ed78c-3237-4c52-bae3-d22c79c74679)

This should not happen.

Desired Solution: Neither add a CSP-configuration for the extension, nor remove the script part

**Comment by xperseguers** [comment]
Please suggest a CSP-configuration.
