### ISSUE TITLE
v2.2.2 | Scheduler Tasks broken, due to addMessage in BatchResizeAdditionalFieldProvider.php

### ISSUE THREAD

**Issue by nfx85** [xperseguers/t3ext-image_autoresize#96]
https://github.com/xperseguers/t3ext-image_autoresize/blob/2da41305c8b10cb33fc67cc3a0430c98e42adb1b/Classes/Task/BatchResizeAdditionalFieldProvider.php#L170

the Signature of the baseMethod is:
`
protected function addMessage(ModuleTemplate $moduleTemplate, string $message, ContextualFeedbackSeverity $severity = ContextualFeedbackSeverity::OK): void
`

So PHP throws an error.

**Comment by xperseguers** [comment]
This duplicate #80 and is already fixed in master branch (thus won't be "fixed" another way for v2.2.2).
