### ISSUE TITLE
Missing return type in BatchResizeCommand collide with symfony/console v7

### ISSUE THREAD

**Issue by mediaessenz** [xperseguers/t3ext-image_autoresize#98]
After updating TYPO3 12 with depenencies using composer an update from symfony/console v6 to v7 happens, which breaks TYPO3.

The cause is the missing return type (int) of the execute method inside Causal\ImageAutoresize\Command\BatchResize.

**Comment by xperseguers** [comment]
same as #100, fixed in https://github.com/xperseguers/t3ext-image_autoresize/commit/473bef1189488920fb5184063c2ee75fec58bb93
